<?php
/**
 * DisplayPhoneStatusTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Telgorithm Messaging API
 *
 * In our APIs we use a rate limit. The rate limit is the maximum number of calls you want to allow in a particular time interval. Setting rate limits helps us to provide the best performance of integration between your software and Telgorithm by preventing other clients from affecting you.    Despite the fact that there is no accepted standard for HTTP rate-limiting headers, we were guided by [**IETF draft: RateLimit Fields for HTTP**](https://www.ietf.org/archive/id/draft-ietf-httpapi-ratelimit-headers-05.html).      We use these HTTP headers on APIs endpoints:    ``` RateLimit-Limit: containing the requests quota in the time window; RateLimit-Remaining: containing a non-negative integer which represents the remaining requests quota in the current time window; RateLimit-Reset: amount of seconds when the full quota will be available; ```  Default quotas:  | Endpoint                             | Default            | | ------------------------------------ | ------------------ | | POST `messaging/v1/OutboundMessages` | 100 per 10 seconds       | | POST `messaging/v1/Phones`           | 120 per hour        | | All REST GET endpoints               | 100 per 10 seconds | | REST non-GET endpoints               | 100 per 10 seconds  |  When quota is exceeded, server do not serve the request replying instead with a 429 HTTP status code.    If you need a bigger quota [contact us](mailto:support@telgorithm.com).
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DisplayPhoneStatusTest Class Doc Comment
 *
 * @category    Class
 * @description Phone Status, used in API response models.&lt;p&gt;Possible values:&lt;/p&gt; &lt;ul&gt; &lt;li&gt;&lt;b&gt;Active&lt;/b&gt;: Phone number is ordered and active.&lt;/li&gt; &lt;li&gt;&lt;b&gt;Pending&lt;/b&gt;: Phone number is ordering, but not active yet.&lt;/li&gt; &lt;li&gt;&lt;b&gt;PendingPortIn&lt;/b&gt;: Phone number is in port-in process.&lt;/li&gt; &lt;li&gt;&lt;b&gt;PendingTcrCampaignChange&lt;/b&gt;: Phone number is in process of changing TCR Campaign.&lt;/li&gt; &lt;li&gt;&lt;b&gt;PendingMessagingConfigAdd&lt;/b&gt;: Phone number is ordered, but it&#39;s not associated with any MessagingConfig.&lt;/li&gt; &lt;li&gt;&lt;b&gt;PendingTcrCampaignAdd&lt;/b&gt;: Phone number is ordered, but it&#39;s not associated with an approved TCR Campaign.&lt;/li&gt; &lt;li&gt;&lt;b&gt;CanadianTrafficOnly&lt;/b&gt;: Phone number belongs to Canada and has no approved TCR Campaign. Only messages to Canada are allowed.&lt;/li&gt; &lt;li&gt;&lt;b&gt;Removed&lt;/b&gt;: Phone number is Removed.&lt;/li&gt; &lt;/ul&gt;
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DisplayPhoneStatusTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DisplayPhoneStatus"
     */
    public function testDisplayPhoneStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
